### ISSUE TITLE
Hello, I would like to ask if the RTB module mentioned in the article is not reflected in the code. In addition, the structure of the code model is not the same as what is proposed in the article. In the encoder as a whole, it is the same as the original Restormer. Is there a problem with my understanding?

### ISSUE THREAD

**Issue by Vibe53** [ztMotaLee/Regformer#2]
Hello, I would like to ask if the RTB module mentioned in the article is not reflected in the code. In addition, the structure of the code model is not the same as what is proposed in the article. In the encoder as a whole, it is the same as the original Restormer. Is there a problem with my understanding?

**Comment by ztMotaLee** [comment]
Thanks for your attention in our work. As illustrated in our paper, we do
not employ a mask in the attention mechanism in the encoder part, and it is
similar to Restormer's architecture. However, in our feed forward network,
we use a mixed scale modeling strategy using different receptive fields
(for the main paper, we choose two branches with kernel sizes of 3 and 5,
which is also different from Restormer.)
The RTB module in the decoder part is illustrated in the main network's
forward function, and we will encapsulate RTB into a function later. For
more details, please check our newest version of arXiv paper.
